### ISSUE TITLE
Blank page after vtiger login

### ISSUE THREAD

**Issue by francescobianco** [javanile/vtiger#32]
And it is running but getting white page after login as admin admin
In host already mysql server is running but what about connectivity with the host db

**Comment by francescobianco** [comment]
Which version of Vtiger Image you use?

**Comment by zahurulhaq** [comment]
Vtiger docker image latest version 7.1

**Comment by zahurulhaq** [comment]
Should I add db properties in docker file and build the image ?

**Comment by francescobianco** [comment]
@zahurulhaq did you have a docker-compose.yml file? please paste here?

**Comment by zahurulhaq** [comment]
No I am using from docker hub as docker file

**Comment by francescobianco** [comment]
I thinks you need follow this to have a proper setup https://github.com/javanile/vtiger-demo

**Comment by datalabsindia** [comment]
```yaml
version: '3'

services:

  vtiger:
    image: javanile/vtiger:7.1.0
    environment:
      - VT_SITE_URL=http://localhost:8080
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8080:80
    volumes:
      - ./:/app
      - vtiger:/var/lib/vtiger
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw

volumes:
  mysql:
  vtiger:
```
