### ISSUE TITLE
How do I set the initial login password

### ISSUE THREAD

**Issue by qiaofeng1227** [javanile/vtiger#41]
From your dockerfile, I found that this environment variable(VT_ADMIN_PASSWORD) is used to set the initial password
```
ENV VT_ADMIN_USER="admin" \
    VT_ADMIN_PASSWORD="admin" \
    VT_ADMIN_EMAIL="admin@localhost.lan" \
    VT_CURRENCY_NAME="USA, Dollars" \
    VT_SCHEDULER=1 \
    VT_INSTALL=1 \
    MYSQL_HOST="mysql" \
    MYSQL_DATABASE="vtiger"
```
In my docker compose file, even if it is set, it will not take effect.
```
  vtiger:
    image: javanile/vtiger:${APP_VERSION}
    container_name: ${APP_NAME}
    restart: always
    ports:
      - ${APP_PORT}:80
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${DB_MYSQL_USER}
      - MYSQL_DATABASE=${DB_MYSQL_NAME}
      - MYSQL_PASSWORD=${DB_MYSQL_PASSWORD}
      - VT_ADMIN_USER=admin
      - VT_ADMIN_PASSWORD=123456
```
